### ISSUE TITLE
EXCHANGE TABLES mistake

### ISSUE THREAD

**Issue by ikeniborn** [ClickHouse/dbt-clickhouse#115]
Code: 60. DB::Exception: Table analitics.__dbt_exchange_test_0 doesn't exist. (UNKNOWN_TABLE) (version [22.11.1.136](https://22.11.1.136/)0 (official build))

14:41:13  clickhouse adapter: ClickHouse server does not support the EXCHANGE TABLES command
14:41:13  clickhouse adapter: This can be caused by an obsolete ClickHouse version or by running ClickHouse on
14:41:13  clickhouse adapter: an operating system that does not support the low level renameat2() system call.
14:41:13  clickhouse adapter: Some DBT materializations will be slower and not atomic as a result.

Core:
  - installed: 1.3.1
  - latest:    1.3.1 - Up to date!

Plugins:
  - postgres:   1.3.1 - Up to date!
  - clickhouse: 1.3.1 - Up to date!

**Comment by genzgd** [comment]
This is an informational message.  As it says, your ClickHouse server does not support the EXCHANGE TABLES command (the most common cause of this is running ClickHouse in Docker on Mac M1, but it can also be due to an out of date Linux kernel.  As the message says, this can affect the performance of some operations but dbt will stillw ork.

**Comment by genzgd** [comment]
In this particular case that table should have existed however.  Were there any other errors in the log before the "UNKNOWN TABLE" error?

**Comment by ikeniborn** [comment]
There were no other errors and the table existed. The error is constant whether there is a table or not. There was no such problem on the CH 22.10 version. Now CH the assembly from Altinita in the specified version.

**Comment by ikeniborn** [comment]
I see an error every time
Code: 60. DB::Exception: Table `analitics`.`__dbt_exchange_test_0` doesn't exist. (UNKNOWN_TABLE) (version 22.11.1.1360 (official build))
It is not clear why he is looking for this table. How to turn off this behavior?

**Comment by genzgd** [comment]
It is a temporary table that dbt-clickhouse uses to determine whether ClickHouse supports the EXCHANGE TABLE command.  Two tables, `__dbt_exchange_test_0` and `__dbt_exchange_test_1` are created and then swapped with the ClickHouse `EXCHANGE TABLE` command (and then dropped).

Are you running multiple DBT instances?  It is possible that multiple instances could be using the same table names and conflicting.  Is there anything in the query logs.

Finally if you know that your ClickHouse server supports EXCHANGE TABLE you can disable this check entirely by setting `check_exchange: false` in your profile/configuration.

**Comment by ikeniborn** [comment]
i use one instance of dbt.
i set the parameter to profile/configuration. Message no longer appears. Thank's!!!
