### ISSUE TITLE
"JSONExtract" DB::Exception: Syntax error

### ISSUE THREAD

**Issue by MaxOrelus** [ClickHouse/dbt-clickhouse#118]
The plugin doesn't seem to add JSONExtract syntax. I've used the query in the playground and it works, but when ran through dbt, it has compile errors.

**Comment by genzgd** [comment]
In most cases the plugin doesn't do anything with the SQL and passes it to ClickHouse directly, so the vast majority of ClickHouse functions should work -- could you please provide the SQL you are using and the error message?

**Comment by MaxOrelus** [comment]
You are right, must of been a typo on my end. Thanks for the clarification.
