### ISSUE TITLE
minor: trailing space in on_cluster_clause()

### ISSUE THREAD

**Issue by tema-popov** [ClickHouse/dbt-clickhouse#124]
Hi!

I want to use `on_cluster_clause` in my `dbt run-operation` macros but it introduces line brakes. 

If we look at [code](https://github.com/ClickHouse/dbt-clickhouse/blob/641e49dfaa9354bb2899900437168339162543a4/dbt/include/clickhouse/macros/materializations/table.sql):

```
{% macro on_cluster_clause(label) %}
  {% set active_cluster = adapter.get_clickhouse_cluster_name() %}
  {%- if active_cluster is not none %}
    ON CLUSTER {{ active_cluster }}
  {%- endif %}
{%- endmacro -%}
```

I can see two things:
1. no whitespace control after if/endif statements
2. unused label variable

I'm curious is line break left for some purpose or is it safe to patch it. Thanks!

**Comment by genzgd** [comment]
All sorts of dbt macros introduce line breaks, so the whole package is dependent on them having no effect when sent to ClickHouse.   Feel free to clean it up -- I definitely missed some `-`s in the macro statements.

The label variable is included for backward compatibility in case anyone was using this macro with the label, but it really made no sense.
