### ISSUE TITLE
can't use with for the table

### ISSUE THREAD

**Issue by SuperEdison** [ClickHouse/dbt-clickhouse#158]
### Describe the bug
with t1 as (select * from xxx)
select * from t1
it's normal in clickhouse but it's abnormal in dbt compile, dbt will use the env's param schema name

**Comment by jesperbagge** [comment]
In dbt your query should be written like 

```sql
with t1 as (
  select
    *
  from {{ ref('model_name') }}
)
select * from t1
```

or

```sql
with t1 as (
  select 
    *
  from {{ source('source_name','table_name') }}
)
select * from t1
```

dbt will know which schema your models or sources are in since you define these in your `dbt_project.yml` or `schema.yml` files.

**Comment by genzgd** [comment]
I don't understand what behavior you think should be changed?

**Comment by genzgd** [comment]
What is the complete SQL and where are you using it?  `with` statements normally work just fine.

**Comment by genzgd** [comment]
Again, where are you using this in DBT?  In a model?  In a source?  In a macro?

The volume testing example taxi uses the following complex `with` statement successfully:

```sql
with (select start, end from {{ ref('trips_rand') }} ORDER BY date_time DESC LIMIT 1) as range,
(select count() from {{ ref('trips_rand') }}) as run_num

select rand() as rand_trip_id, * EXCEPT trip_id, run_num, trip_id as orig_id from {{ source('taxis_source', 'trips') }}
  LEFT JOIN numbers(24) as sysnum ON 1 = 1
  where bitAnd(orig_id, 1023) between range.1 and range.2]
```
