### ISSUE TITLE
Don't drop temp table *__dbt_new_data_00419699_d042_4948_af87_2e0e83de0361

### ISSUE THREAD

**Issue by ikeniborn** [ClickHouse/dbt-clickhouse#159]
### Describe the bug
Not permanent drop tem table with incremental model delete+insert 

### Steps to reproduce
1. create model with parametr
    materialized = "incremental",
incremental_strategy='delete+insert',
 incremental_predicates=[
      ["toYYYYMMDD(toStartOfDay(dttm)) in (", get_incremental_period(env_var('DBT_ENV_CUSTOM_ENV_INCREMENTAL_PERIOD')| int,env_var('DBT_ENV_CUSTOM_ENV_INCREMENTAL_SHIFT')| int,"day"),")"]|join("")
    ],
3. start model from airflow and KubernetlesPodExecutor
4. temp table dont drop afte update, but table empty

### Code examples, such as models or profile settings
clickhouse:
  target: default
  outputs:
    default:
      driver: native
      type: clickhouse
      schema: default
      user: "{{ env_var('DBT_ENV_SECRET_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
      #optional fields
      port: 9000
      host: "{{ env_var('DBT_ENV_SECRET_HOST') }}"
      # host: 31.44.82.109
      verify: False
      secure: False
      connect_timeout: 60
      # compression: 'gzip'
      threads: 8
      send_receive_timeout: 100000
      check_exchange: False
      # Native (clickhouse-driver) connection settings
      sync_request_timeout: 5
      compress_block_size: 1048576
      use_lw_deletes: true

config:
  partial_parse: true
  static_parser: true
  use_experimental_parser: true

{{ config(
  enabled = true,
  schema = 'staging',
  tags = ["overflow_last","overflow_2_1","overflow_full","update_table_ttl"],
  ALTER
  unique_key = ['token_a_id','token_b_id','toYYYYMMDD(toStartOfDay(dttm))'],
  incremental_strategy='delete+insert',
  incremental_predicates=[
      ["toYYYYMMDD(toStartOfDay(dttm)) in (", get_incremental_period(env_var('DBT_ENV_CUSTOM_ENV_INCREMENTAL_PERIOD')| int,env_var('DBT_ENV_CUSTOM_ENV_INCREMENTAL_SHIFT')| int,"day"),")"]|join("")
    ],
  order_by =('toYYYYMMDD(toStartOfDay(dttm))','token_a_id','token_b_id'),
  engine = "MergeTree()",
  partition_by = "toYYYYMMDD(toStartOfMonth(dttm))",
  pre_hook = [
    "set max_bytes_before_external_group_by=1000000000, 
    max_bytes_before_external_sort=500000000, 
    join_algorithm = 'auto',
    join_on_disk_max_files_to_merge = 2,
    partial_merge_join_optimizations = 1,
    partial_merge_join_rows_in_right_blocks = 1000,
    max_bytes_in_join=1000000000"
  ],
) }} 
{{ stg_fct_pair_price_channel_cointegration(
    ref("stg_fct_pair_price")
    ,env_var('DBT_ENV_CUSTOM_ENV_INCREMENTAL_PERIOD')| int
    ,env_var('DBT_ENV_CUSTOM_ENV_INCREMENTAL_SHIFT')| int
    ,"day"
    ,180
  ) 
}}

#### Environment
* dbt version: 1.4.5
* dbt-clickhouse version: 1.4.1
* clickhouse-driver version (if using native)
* clickhouse-connect version (if using http):
* Python version: 
* Operating system: 

#### ClickHouse server
* ClickHouse Server version: ClickHouse 23.4.2.11
* ClickHouse Server non-default settings, if any:
set enable_optimize_predicate_expression=1 , max_block_size = 65536 , max_partitions_per_insert_block = 0, max_memory_usage=200000000000, max_bytes_before_external_group_by=100000000000,  max_bytes_before_external_sort=50000000000, max_threads=128, max_insert_threads=64, max_query_size=524288, allow_nondeterministic_mutations=1

**Comment by genzgd** [comment]
This could happen if there is an error after the temp table is created but before it is cleaned up after processing.  There's not any easy way to fix that situation, since there's nothing like a "finally" block in a DBT macro, and there's no simple method to delete any previous temp tables without a lot of extra code.

I'm open to suggestions for a way to fix this, or if you see some bug in the macros/code that I'm missing.

**Comment by genzgd** [comment]
No updates, plus the Airflow use of dbt-clickhouse is unstable and impossible to debug.
