### ISSUE TITLE
Incompatible return type `ClickHouseConnectionManager.execute`

### ISSUE THREAD

**Issue by PrVrSs** [ClickHouse/dbt-clickhouse#161]
### Describe the bug
`run_hooks` method raise exception: `Attribute: 'str' object has no attribute '_message'`. 
https://github.com/dbt-labs/dbt-core/blob/v1.4.1/core/dbt/task/run.py#L366

### Steps to reproduce
1. Create macro
```
{% macro parity_str_udf %}

CREATE FUNCTION parity_str AS (n) -> if(n % 2, 'odd', 'even');

{% endmacro %)
```
2. dbt run

### Expected behaviour
No exception.
### Code examples, such as models or profile settings
`dbt_project.yml`

```
on-run-start:
- {{ parity_str_udf() }}
```
#### Environment
* dbt version: 1.4.x
* dbt-clickhouse version: 1.4.2

ClickHouseConnectionManager.execute must return: `Tuple[AdapterResponse, agate.Table]`
Now: `Tuple[str, agate.Table]`

**Comment by genzgd** [comment]
Thanks for your report and PR -- this seems like it would have been broken for quite some time, do you why this issue is just showing up now?

**Comment by PrVrSs** [comment]
I don't know. I recently started using dbt.
