### ISSUE TITLE
SYSTEM SYNC REPLICA call in exchange_tables_atomic macro missing space

### ISSUE THREAD

**Issue by damirbk** [ClickHouse/dbt-clickhouse#167]
### Describe the bug

The fix implemented in #156 will format the SQL in the following way:
```sql
SYSTEM SYNC REPLICA

ON CLUSTER "{cluster}"db.table_name
```

As you can see, compared to [the documentation](https://clickhouse.com/docs/en/sql-reference/statements/system#sync-replica), there is a space missing between the ON CLUSTER clause and the db.table_name.

### Expected behaviour

The rendered SQL should look like this:
```sql
SYSTEM SYNC REPLICA

ON CLUSTER "{cluster}" db.table_name
```
So simply a space should be added.

#### Environment
* dbt-clickhouse version: 1.4.2

**Comment by genzgd** [comment]
PR with fix has been merged and released in 1.4.4
