### ISSUE TITLE
Table created with nullable column

### ISSUE THREAD

**Issue by mtieuso** [ClickHouse/dbt-clickhouse#175]
**Is your feature request related to a problem? Please describe.**
ClickHouse do support NULLABLE column (https://clickhouse.com/docs/en/sql-reference/data-types/nullable) (However, this is not **recommended**).

Although, sometimes there is a need to create a nullable column within dbt operation (creating tmp table,...)
For the output table of a dbt-model, I can use pre-hook to create table manually, but this appoarch would not work with auto generated tables of dbt (_tmp table, or _backup)

**Describe the solution you'd like**
There is a config that allows defining nullable columns.

**Describe alternatives you've considered**

**Additional context**

**Comment by simpl1g** [comment]
Column type in created table is detected by column type from SELECT. No need in any settings. Just make your column `Nullable` type in query, otherwise you will not be able to insert data if your select differs from table.

```sql
SELECT toNullable(1) AS col
```

This will create table with column type `col Nullable(UInt8)`

**Comment by mtieuso** [comment]
@simpl1g thanks for your suggestion. 
I just find out that if columns are not in order, uniq,... they will be configured as Nullable as default.
My previous mistake is not casting type of clickhouse in correct way: 
- `select created_at::date` >> DB::Exception: Cannot convert NULL value to non-Nullable type: while executing.
- `select toDate(created_at)` >> it works.
