### ISSUE TITLE
Support setting TTL for table/incremental materializations 

### ISSUE THREAD

**Issue by tema-popov** [ClickHouse/dbt-clickhouse#187]
**Is your feature request related to a problem? Please describe.**
I have a case where I want to create incremental materialization and support row-level TTL for a model. I don't see a clear way or any workaround how to achieve it.

**Describe the solution you'd like**
Table Materialization Option `ttl` in the same way as `engine`, `order_by`, `partition_by`

I would appreciate a workaround if there is any, thanks!

**Comment by genzgd** [comment]
This should be fixed by #254, released in v1.7.6
