### ISSUE TITLE
Failure to create database on cluster that contains a dash `-` character in the name 

### ISSUE THREAD

**Issue by the4thamigo-uk** [ClickHouse/dbt-clickhouse#198]
### Steps to reproduce
1. Setup a cluster with a dash in the cluster name
2. Setup a new dbt project pointing to the cluster with cluster mode enabled
3. `dbt run`
4. `Failed to create dbt_dev database due to ClickHouse exception`

### Expected behaviour
The dbt pipeline should be created

I believe this line should have double quotes around the cluster name  : 

https://github.com/ClickHouse/dbt-clickhouse/blob/main/dbt/adapters/clickhouse/dbclient.py#L153

**Comment by genzgd** [comment]
Fixed in 1.4.9
