### ISSUE TITLE
on_schema_change not working as expected in incremental models

### ISSUE THREAD

**Issue by damirbk** [ClickHouse/dbt-clickhouse#199]
dbt supports an optional [on_schema_change](https://docs.getdbt.com/docs/build/incremental-models#what-if-the-columns-of-my-incremental-model-change) setting for configuring behaviour when the schema changes in an incremental model. From what I can see, the dbt-clickhouse plugin doesn't support this feature.

It would be great if it could be supported, since it's quite a useful feature for incremental models!

**Comment by genzgd** [comment]
There is definitely some macro code that appears to support the `on_schema_change` setting.  Can you provide a reproducible example where it's not behaving as expected?

**Comment by damirbk** [comment]
Yes, of course!

Let's say I have the following dbt model:

```sql
{{
    config(
        materialized='incremental',
        unique_key='col_1',
        on_schema_change='ignore'
    )
}}

{% if not is_incremental() %}
select
    number as col_1,
    number + 1 as col_2
from numbers(3)
{% else %}
select
    number as col_1,
    number + 1 as col_2,
    number + 2 as col_3
from numbers(2, 3)
{% endif %}
```

It's set up such that you can just `dbt run` it twice (run it with `--full-refresh` the first time if the table already exists) and the first time it will look like this:

| col_1 | col_2 |
|-------|-------|
| 0     | 1     |
| 1     | 2     |
| 2     | 3     |

When running it the second time, with setting `on_schema_change='ignore'`, it should look like this:

| col_1 | col_2 |
|-------|-------|
| 0     | 1     |
| 1     | 2     |
| 2     | 3     |
| 3     | 4     |
| 4     | 5     |

Which it does.

With setting `on_schema_change='fail'`, it should just fail. Instead, the same output is produced.

With setting `on_schema_change='append_new_columns'`, it should look like this:

| col_1 | col_2 | col_3 |
|-------|-------|-------|
| 0     | 1     | null  |
| 1     | 2     | null  |
| 2     | 3     | 4     |
| 3     | 4     | 5     |
| 4     | 5     | 6     |

Instead, it looks the same as the result with `on_schema_change='ignore'`.

With setting `on_schema_change='sync_all_columns'`, it should look the same as `append_new_columns`, because we're just adding new columns. However, we have the same result as `ignore`.

Let's say instead I have the following SQL:

```sql
{{
    config(
        materialized='incremental',
        unique_key='col_1',
        on_schema_change='ignore'
    )
}}

{% if not is_incremental() %}
select
    number as col_1,
    number + 1 as col_2
from numbers(3)
{% else %}
select
    number as col_1,
    number + 2 as col_3
from numbers(2, 3)
{% endif %}
```

All I did was remove `col_2` from the incremental select.

With any `on_schema_change` setting, this model fails the second time it's run (and actually removes overlapping rows from the materialized table!).

Expected results are:
`on_schema_change='ignore'`:
| col_1 | col_2 |
|-------|-------|
| 0     | 1     |
| 1     | 2     |
| 2     | null  |
| 3     | null  |
| 4     | null  |

(Perhaps the 3rd row should be | 2 | 3 |, not sure...)

`on_schema_change='fail'`: The model fails.

`on_schema_change='append_new_columns'`:
| col_1 | col_2 | col_3 |
|-------|-------|-------|
| 0     | 1     | null  |
| 1     | 2     | null  |
| 2     | null  | 4     |
| 3     | null  | 5     |
| 4     | null  | 6     |

(Perhaps the 3rd row should be | 2 | 3 | 4 |, not sure...)

`on_schema_change='sync_all_columns'`:
| col_1 | col_3 |
|-------|-------|
| 0     | null  |
| 1     | null  |
| 2     | 4     |
| 3     | 5     |
| 4     | 6     |

`sync_all_columns` should apparently also support data type changes, but that exercise is left to the reader :)

**Comment by genzgd** [comment]
Thanks for the detail!  As I said, there is some code which looks like it supports `on_schema_change`, but there aren't any tests around it and having examples to start implementing such tests will make it much easier to get it working correctly.
