### ISSUE TITLE
Deduplication when using ReplicatedMergeTree with delete+insert incremental strategy 

### ISSUE THREAD

**Issue by the4thamigo-uk** [ClickHouse/dbt-clickhouse#213]
### Steps to reproduce
1. build an incremental model using Replicated merge tree and delete+insert strategy
2. populate the model as full refresh
3. re-run as incremental
4. re=run as incremental

### Expected behaviour
step 4 should delete the records inserted in step 3 and reinsert them

### Actual behaviour
The records are not reinserted in step 4

# Explanation

It looks like when you insert exactly the same set of records in the incremental update, the replication deduplication mechanism kicks in and ignores the new block of rows. 

I am working around this by adding an `alter table... modify setting` hook, but it is not ideal. It would be nice if I could specify this as a setting when the table is created, or alternatively that it is set automatically when using the delete+insert strategy, as otherwise it wouldnt be guaranteed to work.

**Comment by genzgd** [comment]
Just to clarify, the problem is that in Step 4, the lightweight  DELETE occurs, but the reinsert does not because of built in ClickHouse deduplication, so those records are just missing?

It seems reasonable to disable deduplication for the destination table, I'll take a look.

**Comment by the4thamigo-uk** [comment]
Yep thats what seems to happen.

**Comment by genzgd** [comment]
For the short term it seems like intead of using a hook you should be able to add the `insert_deduplicate: 0` into the model `config` settings, which should be automatically picked up by this code:

```
 @available
    def get_model_settings(self, model):
        settings = model['config'].get('settings', dict())
        res = []
        for key in settings:
            res.append(f' {key}={settings[key]}')
        return '' if len(res) == 0 else 'SETTINGS ' + ', '.join(res) + '\n'
```

Is that a fix you can validate quickly?

My current thought is to add `insert_deduplicate: 0` automatically into this method as a fix, and have an override configuration value if the user really wants to leave ClickHouse deduplication on.

**Comment by the4thamigo-uk** [comment]
Ah that looks like a neater solution. Give me 15mins to try it out.

**Comment by the4thamigo-uk** [comment]
```
16:44:09  Database Error in model int_sales__daily__external2 (models/intermediate/sales/int_sales__daily__external2.sql)
16:44:09    :HTTPDriver for http://clickhouse-prod.dragonite.venatusmedia.com:8123 returned response code 404)
16:44:09     Code: 115. DB::Exception: There was an error on [chi-repl-04-23-ch-prod-0-1:9000]: Code: 115. DB::Exception: Unknown setting insert_deduplicate: for storage ReplicatedMergeTree. (UNKNOWN_SETTING) (version 23.10.3.5 (official build)). (UNKNOWN_SETTING) (version 23.10.3.5 (official build))
```

**Comment by the4thamigo-uk** [comment]
For reference I added it like this : 

```
{{
  config(
    ...
    settings={
      'insert_deduplicate':0
    }
  )
}}
```

**Comment by the4thamigo-uk** [comment]
Oh, these are table level settings... I figured these were settings on the INSERT?

**Comment by the4thamigo-uk** [comment]
Yeah the above works... thanks... I wasnt aware you could set the table SETTINGS this way.

**Comment by the4thamigo-uk** [comment]
Probably need the `settings` option in the readme?

**Comment by genzgd** [comment]
cool, that seems like a reasonable solution.  And yeah, I think that needs to be called out better in the documentation.

**Comment by the4thamigo-uk** [comment]
Still maybe worth defaulting to this option for this strategy, do you think?

**Comment by genzgd** [comment]
Yes, I think it's a good default for any of the dbt incremental strategies.  The ClickHouse automatic deduplication is sort of an unexpected gotcha in such a high level tool.
