### ISSUE TITLE
Storage policy settings

### ISSUE THREAD

**Issue by gabriel-suela** [ClickHouse/dbt-clickhouse#224]
### Describe the bug
Im trying to add storage policy for my table in settings, but cant manage to do it. Already tried in many ways, but i keep getting this error
```
{{
    config(
        materialized='table',
        settings = {"storage_policy": "gcs_main"}
    )

}}
```

and getting this error:

```Database Error in model City (models/clickhouse/City.sql)
[dbt:run:clickhouse:select] 17:42:53     Code: 62. DB::Exception: Syntax error: failed at position 346 ('empty') (line 17, col 9): empty
[dbt:run:clickhouse:select] 17:42:53        as (
[dbt:run:clickhouse:select] 17:42:53
[dbt:run:clickhouse:select] 17:42:53    with source as (
[dbt:run:clickhouse:select] 17:42:53      select id, code, name, ddd
[dbt:run:clickhouse:select] 17:42:53      from prod_icv.City
[dbt:run:clickhouse:select] 17:42:53    )
[dbt:run:clickhouse:select] 17:42:53
[dbt:run:clickhouse:select] 17:42:53    select * from source
[dbt:run:clickhouse:select] 17:42:53        )
[dbt:run:clickhouse:select] 17:42:53            . Expected one of: token, Dot, OpeningRoundBracket, end of query. (SYNTAX_ERROR) (version 23.10.5.20 (official build))```

**Comment by genzgd** [comment]
Can you possibly get the full SQL query from the ClickHouse `system.query_log` or create a reproducible example?  Simple settings seem to work correctly (see, for example, the tests [here](https://github.com/ClickHouse/dbt-clickhouse/blob/main/tests/integration/adapter/clickhouse/test_clickhouse_table_materializations.py#L59-L64) work okay, so it's not clear what happening with your model.

**Comment by gabriel-suela** [comment]
managed to make it work. it was "simple", just added simple quotes inside double quotes on the value:

```
settings = {"storage_policy": "**'gcs_main'**"}
```
