### ISSUE TITLE
materialization comment in metadata

### ISSUE THREAD

**Issue by dstsimokha** [ClickHouse/dbt-clickhouse#227]
I just want to add the possibility to write the comment in materialization metadata in Clickhouse

Tested it and it can be done by adding a few lines of code, for example, in [view materialization](https://github.com/ClickHouse/dbt-clickhouse/blob/ca9da0b6ebacc14d67139b0b417e0d4083b68a9c/dbt/include/clickhouse/macros/materializations/view.sql#L81) right after `as ( {{ sql }} )` like that:
```
...
  as (
    {{ sql }}
  )
    {% set comment = config.get('comment') %}
    {% if comment %}
      COMMENT '{{ comment }}'
    {% else %}
      COMMENT 'DBT'
    {%- endif %}
...
```

And with the customised `comment` in schema.yml it will be in CH
```
version: 2
models:
  - name: MODEL_NAME
    config:
      comment: SOME CUSTOM COMMENT
```

I can add it by myself and request a merge, but I'm totally new to contributing to anything at all so will be glad if somebody can guide how to contribute correctly :)

**Comment by simpl1g** [comment]
I guess adapter already supports docs. See example tests here https://github.com/ClickHouse/dbt-clickhouse/tree/main/tests/integration/adapter/persist_docs.

`description` field from model should be saved to COMMENT section

**Comment by dstsimokha** [comment]
@simpl1g adapter supports docs for sure, but there is no option to write to Clickhouse-specific COMMENT field in table's or view's metadata

Not sure that dbt's `description` and Clickhouse's `comment` should be equalized here - `comment` is by definition a more broader and free-form field without specific function, while `description` serves one exact goal.

**Comment by simpl1g** [comment]
@dstsimokha 
>Not sure that dbt's description and Clickhouse's comment should be equalized here

They are already equalized, this is what persist docs does. It saves `description` in `comment` via `MODIFY COMMENT`, [code is here](https://github.com/ClickHouse/dbt-clickhouse/blob/ca9da0b6ebacc14d67139b0b417e0d4083b68a9c/dbt/include/clickhouse/macros/persist_docs.sql#L16-L19C16)

**Comment by dstsimokha** [comment]
Not from the first try, but I got the `persist_docs` functionality
