### ISSUE TITLE
dbt creates temporary tables for incremental load, is there a way to auto delete these?

### ISSUE THREAD

**Issue by athlatif** [ClickHouse/dbt-clickhouse#229]
### Describe the bug
whenever i create a table with incremental materialisation configs i end up having temporary tables, is there a way to get rid of these tables?

dim_table__dbt_new_data_01128add_58b2_48e7_a82b_10baac4d9ec6 

<img width="379" alt="Screenshot 2023-12-24 at 1 04 27 pm" src="https://github.com/ClickHouse/dbt-clickhouse/assets/42766508/b5292771-5c60-48cc-a530-fc6909804634">
  

### Code examples, such as models or profile settings

```

{{
    config(
        materialized='incremental',
        on_schema_change='sync_all_columns',
        unique_key='id',
        incremental_strategy='delete+insert',
        tags = ['tag']
    )
}}
WITH src_table AS (
    select * from {{ref('src_table')}}
)

SELECT
    *
FROM
    (
        SELECT
            *,
            row_number() OVER (
                PARTITION BY
                    id
                ORDER BY
                    updated_at DESC
            ) AS r
        FROM
            src_table
    )
where
    r = 1

{% if is_incremental() %}

  where updated_at > (select max(updated_at) from {{ this }})

{% endif %}
```

#### Environment
* dbt-clickhouse version: 1.4.8

#### ClickHouse server
* ClickHouse Server version:  23.3.8

**Comment by genzgd** [comment]
Normally the new data tables are cleared up automatically by code within the incremental materialization macros.  If there is some of kind error during the materialization that cleanup may not happen, so you should check the dbt and ClickHouse server logs.

If you are using a `clustered` setup you should definitely upgrade to dbt-clickhouse 1.4.9 or later, which has improved support for distributed/on cluster operations.

**Comment by athlatif** [comment]
@genzgd would it be an issue to delete all these tmp tables? i am thinking of building a pipeline that drops these tables

**Comment by genzgd** [comment]
It should be perfectly fine to drop any tables that are clearly incremental materialization temp tables.

**Comment by athlatif** [comment]
many thanks!
