### ISSUE TITLE
settings is not passed to CREATE VIEW AS

### ISSUE THREAD

**Issue by lksv** [ClickHouse/dbt-clickhouse#231]
### Steps to reproduce

I need to pass settings to `CREATE VIEW AS`, specifically `CREATE VIEW ... AS (...) SETTINGS flatten_nested=0` .

However, when I create a model (view) as follows, the setting is not used.

```
{{
    config(
        materialized='view',
        settings={'flatten_nested': 0},
    )
}}
```

I suspect the solution is to add `{{ adapter.get_model_settings(model) }}` to the [clickhouse__create_view_as macro](https://github.com/ClickHouse/dbt-clickhouse/blob/ca9da0b6ebacc14d67139b0b417e0d4083b68a9c/dbt/include/clickhouse/macros/materializations/distributed_table.sql#L117) and also to [materialed_view](https://github.com/ClickHouse/dbt-clickhouse/blob/v1.7.1/dbt/include/clickhouse/macros/materializations/materialized_view.sql)

Currently, I use workaround with `pre_hook="SET flatten_nested=0"`. Howerever, as the [README](https://github.com/ClickHouse/dbt-clickhouse#set-statement-warning) mentions, it is not recomended to use `SET`.

### Expected behavior

* dbt version: 1.7.4
* dbt-clickhouse version: 1.7.1
* clickhouse-driver version (if using native): 0.2.6
* Python version: 3.10.12
* Operating system: Linux (ubuntu 23.10.)

#### ClickHouse server
* ClickHouse Server version: 23.8.8

**Comment by BentsiLeviav** [comment]
Hi @lksv 
Just created a PR for solving this in #249
