### ISSUE TITLE
Incorrect schema in materialized_view to <schema>.<table>

### ISSUE THREAD

**Issue by ikeniborn** [ClickHouse/dbt-clickhouse#238]
When creating a view for a target table, the schema is not selected correctly.
Core:

installed: 1.7.4
latest: 1.7.4 - Up to date!
Plugins:

clickhouse: 1.7.1 - Up to date!
Clickhouse:
ClickHouse 23.12.1.1368

{{ 
  config(
    enabled = true
    ,schema = 'dimension'
    ,tags = ["model_token"]
    ,materialized = "materialized_view"
    ,engine = "ReplicatedReplacingMergeTree ('/clickhouse/tables/{shard}/{uuid}','{replica}', updated_dttm)"
    ,settings = { 'index_granularity': 8192 }
    ,order_by = ('token_id','crowdsales_id','crowdsales_source')
      ,post_hook = [
      "{{update_table_ttl(this,'updated_dttm',1,'day')}}"
    ]
  ) 
}}
select
  t0.token_id
  ,t0.crowdsales_id
  ,t0.crowdsales_source
  ,t0.crowdsales_platform_id
  ,t0.crowdsales_num
  ,t0.crowdsales_lockup_period
  ,t0.crowdsales_type
  ,t0.crowdsales_status
  ,t0.crowdsales_start_dttm
  ,t0.crowdsales_end_dttm
  ,t0.crowdsales_is_sponsored
  ,t0.crowdsales_price_usd
  ,t0.crowdsales_quantity
  ,t0.crowdsales_raised_usd
  ,t0.crowdsales_hard_cap_usd
  ,t0.crowdsales_is_valid
  ,now()::DateTime as updated_dttm
from
  {{ref("snap_dim_token_crowdsale")}} t0
order by 
  t0.updated_dttm desc
limit 1 by 
  t0.token_id

-- dimension.dim_token_platform_mv source

CREATE MATERIALIZED VIEW dimension.dim_token_platform_mv TO default.dim_token_platform
(

    `token_id` String,

    `token_platforms` Array(Tuple(String,
 String)),

    `token_platforms_list` Array(String),

    `token_platforms_count` UInt64,

    `updated_dttm` DateTime
) AS
SELECT
    t0.token_id,

    t0.token_platforms,

    t0.token_platforms_list,

    length(t0.token_platforms_list) AS token_platforms_count,

    CAST(now(),
 'DateTime') AS updated_dttm
FROM snapshot.snap_dim_token_platform AS t0
ORDER BY t0.updated_dttm DESC
LIMIT 1 BY t0.token_id;

**Comment by SoryRawyer** [comment]
Hey @ikeniborn I think this might have been addressed in dbt-clickhouse version 1.5.2, released earlier this month. Would you mind trying that out and seeing if you're still having this issue?
