### ISSUE TITLE
Question: Is it possible to set a separate database for local tables using `distributed_table` materialisation? 

### ISSUE THREAD

**Issue by bun4uk** [ClickHouse/dbt-clickhouse#248]

**Comment by emirkmo** [comment]
You mean 

`database_local/shard.table`
`database_distributed.table`

correct?

This is also how we use them allow easier role based access. Would be great.

IIRC, should not be hard to add to the first distributed table PR but I have not kept up with the changes and tests. 

**To generalize, we should add support for table name prefix, suffix, or separate database (same name) for the local and/or distributed tables.**

**Comment by bun4uk** [comment]
Emir, hi! 
Yes, you understood me correct

**Comment by steffen030** [comment]
Hey, I have created a [PR](https://github.com/ClickHouse/dbt-clickhouse/pull/285) that allows to add a prefix to the database of the local table. By that you can filter them and apply dedicated permissions.
