### ISSUE TITLE
Run Cloud tests against SMT

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/dbt-clickhouse#253]
https://clickhouse.com/docs/en/cloud/reference/shared-merge-tree is the new default table engine on ClickHouse Cloud. We must ensure first-class support for SMT in DBT. Some changes to ClickHouse settings are required (tldr: use `select_sequential_consistency` instead of `insert_quorum`) See https://clickhouse.com/docs/en/cloud/reference/shared-merge-tree#settings 

Credentials are available via env vars
- INTEGRATIONS_TEAM_TESTS_CLOUD_HOST_SMT
- INTEGRATIONS_TEAM_TESTS_CLOUD_PASSWORD_SMT

**Comment by BentsiLeviav** [comment]
I created a [branch](https://github.com/ClickHouse/dbt-clickhouse/tree/cloud-tests-against-smt) with an additional GitHub job for testing against the SMT instance.

There are still a few tests failures, due to a bug, will update here once it is being solved.
