### ISSUE TITLE
Adding a comment at the end of a query results in a syntax error

### ISSUE THREAD

**Issue by tevariou** [ClickHouse/dbt-clickhouse#256]
### Steps to reproduce
1. Add a comment at the last line of a model
```
select * 
from {{ ref('some_ref') }}
where id = 1 -- some comment
```
3. Run model
4. Get an error
```
 Code: 62. DB::Exception: Syntax error: failed at position 15 ('(') (line 1, col 15): (select
```

### Expected behaviour

To not raise a syntax error

#### Environment
* dbt version: 1.7.9
* dbt-clickhouse version: 1.7.3
* clickhouse-driver version (if using native): 0.2.6
* clickhouse-connect version (if using http): 0.7.2
* Python version: 3.10.9
* Operating system: MacOS / Linux

#### ClickHouse server
* ClickHouse Server version: 23.8
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by tevariou** [comment]
related: https://github.com/ClickHouse/dbt-clickhouse/pull/212

**Comment by emirkmo** [comment]
to be clear #212 seems to have not solved the problem.

@tevariou  Can you by any chance paste in the compiled code as well as where it actually errors? It seems cutoff.

**Comment by tevariou** [comment]
```
select 
    *
from
    {{ get_source("mimic_iii", 'admissions') }} -- test
```

![Screenshot 2024-03-26 at 15 33 34](https://github.com/ClickHouse/dbt-clickhouse/assets/34629112/5284df54-cf14-4d67-be52-5e1ec06bb217)
