### ISSUE TITLE
invalidate_hard_deletes option does not work with clickhouse

### ISSUE THREAD

**Issue by andrewkomkov** [ClickHouse/dbt-clickhouse#271]
### Describe the bug
invalidate_hard_deletes option (https://docs.getdbt.com/reference/resource-configs/invalidate_hard_deletes) does not work with clickhouse
### Steps to reproduce
1. Create snapshot like this
```
{% snapshot snap_imdb_actors %}
    {{
        config(
          target_schema='snapshots',
          strategy='check',
          unique_key='id',
          check_cols='all',
          invalidate_hard_deletes=True
        )
    }}
    with actors as (
    select * from {{ source('imdb', 'actors') }})

    select * from actors
{% endsnapshot %}
```
2. Run it
3. Then delete a row from table imdb.actors
4. run snapshot again

### Expected behaviour
In snapshot table, row with deleted id should have dbt_valid_to, but it does null

#### Environment
* dbt version: 1.7.12
* dbt-clickhouse version: 1.7.6

**Comment by andrewkomkov** [comment]
I guess i found cause of the problem
If somehow pass this setting SET join_use_nulls = 1;
It will wokr
The question is - how can i pass settings like this to dbt?

**Comment by andrewkomkov** [comment]
![image](https://github.com/ClickHouse/dbt-clickhouse/assets/33517893/78596699-f71d-49a4-a347-32884e0ae1d3)

Fixed with this setting

**Comment by genzgd** [comment]
thanks for the investigation -- my sense is that dbt-clickhouse should make "join_use_nulls" the default perhaps?

**Comment by andrewkomkov** [comment]
I don't think you should make it enabled by default.
Since it is not enabled by default in Clickhouse itself
However, this should be included in the module description
