### ISSUE TITLE
Adding PROJECTION to models

### ISSUE THREAD

**Issue by hohmannr** [ClickHouse/dbt-clickhouse#319]
**Is your feature request related to a problem? Please describe.**
It would be awesome if we could add [projections](https://clickhouse.com/docs/en/sql-reference/statements/alter/projection) to models, this is very helpful when using a semantic layer on top of the data marts, to facilitate and speed up querying for certain filters.

**Describe the solution you'd like**
IMHO, the ideal solution would be to configure the projection as a `config` parameter (not sure though if dbt supports this):

```sql
-- models/marts/touchpoints;
{{
    config(
        materialized='materialized_view',
        engine='MergeTree()',
        order_by='workspace_id, toStartOfHour(updated_at), touchpoint_id',
        projections=[
            { "name": "some_projection", "select": ["touchpoint_id", "some_other_col"], "order_by": ["touchpoint_id"] }
        ]
    )
}}
select * from {{ source('other', 'touchpoints') }}
```

**Describe alternatives you've considered**
The alternative that we use currently is using a migration script to put the projection on various models, after they have been built, which is not really nice, since the code creating a projection and the model are separate from each other and we need to take care that the database migrations are always up to date with the dbt models.

**Comment by stephen-up** [comment]
FWIW. We are adding projections using [post_hooks](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook).

It works alright, But we get timeouts for materializing slow projections. `ClickHouse exception:  The read operation timed out`
<img width="544" alt="image" src="https://github.com/user-attachments/assets/a785d694-bb88-4f6e-8cfb-d5bdc62fd10a">

**Comment by hohmannr** [comment]
@BentsiLeviav Thanks for closing this so fast!
