### ISSUE TITLE
Extra quotes in split_part macro

### ISSUE THREAD

**Issue by 3fonov** [ClickHouse/dbt-clickhouse#337]
### Describe the bug
It seems to be extra quotation in split_part macro. If you run `{{ dbt_utils.get_url_parameter("url","field_name") }}` it results in following code:
```
      nullif(
    splitByChar(''&'', 
    splitByChar(''field_name='', url)[2]
)[1]
,'') as field_name,
```
### Steps to reproduce
1. run macro `{{ dbt_utils.get_url_parameter("url","field_name") }}`

### Expected behaviour

I Expect it to be:
```
      nullif(
    splitByChar('&', 
    splitByChar('field_name=', url)[2]
)[1]
,'') as field_name,
```

**Comment by BentsiLeviav** [comment]
Hi @3fonov 
Thank you for your contribution!

I see that you indented many lines. There is a `lint` process configured in a `Makefile`. Please return back the old format or alternatively run `make lint` in the project root dir to see what you need to adjust back.

Thanks
