### ISSUE TITLE
Ability to set table settings such as index_granularity

### ISSUE THREAD

**Issue by jonkiq** [ClickHouse/dbt-clickhouse#355]
**Is your feature request related to a problem? Please describe.**
I want to set certain settings on the model, such as index_granularity (which is defaulted to 8192)

**Describe the solution you'd like**
Add a table_settings to config() with a dict of key/value pairs

**Describe alternatives you've considered**
Manual process

**Comment by simpl1g** [comment]
According to docs you can pass table level settings to `settings` in model


settings | A map/dictionary of "TABLE" settings to be used to DDL statements like 'CREATE TABLE' with this model |  
-- | -- | --
query_settings | A map/dictionary of ClickHouse user level settings to be used with INSERT or DELETE statements in conjunction with this model
