### ISSUE TITLE
Wrong regex in column.py

### ISSUE THREAD

**Issue by yoavo-datricks** [ClickHouse/dbt-clickhouse#40]
Hi @silentsokolov 
We are trying to work with dbt-clickhouse to write a macro that uses the adapter.get_columns_in_relation function.
We are getting errors regarding parentheses and noticed an issue with DateTime and decimal columns not parsed properly.
I believe the _brackets_regex is wrong and returns the type without the ending parentheses, can this be fixed?

**Comment by silentsokolov** [comment]
Hi @yoavo-datricks, could you provide more details to help me investigate this error? (Error log / Example code)

**Comment by yoavo-datricks** [comment]
I hope this one could better explain the issue
![image (8)](https://user-images.githubusercontent.com/72439961/169251764-7d0027e6-3ff2-41a6-a577-92780a1e30cf.png)

**Comment by yoavo-datricks** [comment]
Solved by fixing the regex
