### ISSUE TITLE
Support to native connection

### ISSUE THREAD

**Issue by vargacypher** [ClickHouse/dbt-clickhouse#67]
I do like to know why dbt-clickhouse no longer support native connection ?
I'm using dbt-clickhouse==1.0.4  because i need to connect with port 9000.

**Comment by genzgd** [comment]
At the moment there is no Python ClickHouse driver that efficiently and reliably support both Native and HTTP, and HTTP is generally more compatible with proxies/firewalls, and VPNs.  There were also multiple requests for HTTP support in https://github.com/ClickHouse/dbt-clickhouse/issues/7.  

We intend to support the native connection in the ClickHouse Connect driver, but that work is some time off.  We'll look into possibly supporting both drivers in the meantime.

**Comment by vargacypher** [comment]
Thank's for the quick response.
We would appreciate it very much if this were possible.

**Comment by guykoh** [comment]
@genzgd put back the native driver (in addition to the HTTP). Thank you Geoff!
@vargacypher you can try to connect now to port 9000, it should work even without specifying the driver=native.

**Comment by genzgd** [comment]
I don't believe the new version has been released yet.  1.1.2 does not
contain the native driver

**Comment by guykoh** [comment]
Sorry about that, I just release a new version - 1.1.3
