### ISSUE TITLE
Missing documentation for `ON CLUSTER`

### ISSUE THREAD

**Issue by mharrisb1** [ClickHouse/dbt-clickhouse#85]
I see it exists:

- https://github.com/ClickHouse/dbt-clickhouse/search?q=on+cluster
- https://github.com/ClickHouse/dbt-clickhouse/blob/1d23e889b7e551d332414d2f63cbe376c00fbce9/dbt/adapters/clickhouse/connections.py#L32-L54

Documenting how to use it would be helpful

**Comment by guykoh** [comment]
Thanks @mharrisb1, CLUSTER is still experimental, this is why we don't have documentation yet.
