### ISSUE TITLE
RENAME EXCHANGE error in dbt-clickhouse==1.1.8

### ISSUE THREAD

**Issue by vargacypher** [ClickHouse/dbt-clickhouse#94]
Hey guys,
I'm having problems in dbt-clickhouse 1.1.8 when I try to run the models (views) that already exist in the database the following error occurs (**code: 48**):
![image](https://user-images.githubusercontent.com/77084039/189123479-fd151206-6226-4846-97b0-d529b30c916d.png)

I downgrade to dbt-clickhouse 1.1.6 and it works normal
![image](https://user-images.githubusercontent.com/77084039/189123458-f84aeec1-52af-42ec-96db-beb6c98e6c6d.png)

**Comment by genzgd** [comment]
Thanks for the report.  I'm guessing your tables are using databases with Ordinary (and not Atomic) engines?

**Comment by vargacypher** [comment]
The tables are all from the Merge Tree family, but I don't think that answers your question.
How can I find out if it's an Atomic or Ordinary database engine?

**Comment by genzgd** [comment]
`SELECT * FROM system.databases` will list the engine.  What ClickHouse version are you on?

Assuming the problem is an "Ordinary" database engine I'll see if I can track down the issue in dbt-clickhouse 1.1.8

**Comment by vargacypher** [comment]
I'm using  version 22.2 and engine is Atomic
![image](https://user-images.githubusercontent.com/77084039/189140222-dc0922d6-4b37-4d06-8649-a7a2c5617b5a.png)

**Comment by genzgd** [comment]
Okay, that means the problem is something else, thanks for the information.

**Comment by vargacypher** [comment]
Thank you for the quick response

**Comment by genzgd** [comment]
It looks like that error is thrown if you are not running ClickHouse on Linux or you are running it on an old Linux version.  What OS is your ClickHouse server on?

In any case we definitely need to update dbt-clickhouse to check if the server supported the Atomic database exchange functionality.

**Comment by vargacypher** [comment]
We're on CentOS 7 in dev.

**Comment by genzgd** [comment]
That probably explains it.  As I read the code atomic exchanges require a Linux Kernel of 3.15 or higher and Centos 7 looks to be on 3.10.  I'm looking into ways to detect that capacity before dbt-clickhouse tries to use exchange instead of rename.

**Comment by vargacypher** [comment]
Okay, I'll stick with dbt-clickhouse 1.1.6 until this issue is resolved.
Thank u so much for the help.

**Comment by genzgd** [comment]
This should work correctly with dbt 1.2.1 and dbt-clickhouse 1.2.1

**Comment by vargacypher** [comment]
Hi @genzgd 
We're having a new problem related to this issue again,  when we try to run de dbt compile we have the error again.
![image](https://user-images.githubusercontent.com/77084039/192641050-3c99bb25-f3ea-40e9-b320-d655adc16b15.png)

Whe we try to run, it show an erro a them completed the task.
![image](https://user-images.githubusercontent.com/77084039/192641648-c3cc4979-80a5-4768-ac43-3422bd6ac64b.png)

Can u help us ?

**Comment by vargacypher** [comment]
@genzgd Thank u so much for the explanation and the help again.

Is there any way we can contribute to your project? We really appreciate the help that u guys give to us.

**Comment by genzgd** [comment]
dbt-clickhouse is completely open source and we welcome code contributions (and bug reports are very helpful too!)
