### ISSUE TITLE
Incremental model ambiguous error

### ISSUE THREAD

**Issue by vargacypher** [ClickHouse/dbt-clickhouse#96]
Hi guys, Sorry for the inconvenience again, but we need some help with incremental models, and sometimes it's hard to find information about dbt and clickhouse, so I'm turning to you guys.

We make an incremental model, and then run it, at the first time it work's normal.
But when we try to run this model again an error occur:

 ```
When searching for a relation, dbt found an approximate match. Instead of guessing 
20:27:09    which relation to use, dbt will move on. Please delete test.ORDERS_INCREMENTAL, or rename it to be less ambiguous.
20:27:09    Searched for: test.orders_incremental
```
![image](https://user-images.githubusercontent.com/77084039/189438517-00c5e49a-6b4f-4e78-b956-06a94317f3d6.png)

My model (ORDERS_INCREMENTAL.sql):
```
{{
    config(
        order_by='(ORDER_STORE,ORDER_DATE,ORDER_ID)',
        engine='MergeTree()',
        materialized='incremental',
        unique_key=['ORDER_ID','ORDER_DATE','ORDER_STORE'],
        inserts_only=True
        )
}}

SELECT ORDER_ID,ORDER_DATE,ORDER_STORE FROM {{source('prod', 'ORDERS')}}
    LIMIT 2

{% if is_incremental() %}

  where ORDER_DATE > (select min(ORDER_DATE) from {{this}})

{% endif %}
```

Am i doing something wrong?

**Comment by konnectr** [comment]
Maybe you change the structure of the model? And because of this, this error occurs?

**Comment by vargacypher** [comment]
Thnk's for answer, so we didn't change anything,  we drop table in the database and try to run twice, it Always work's at the first time but always on the second run it fail's.

**Comment by vargacypher** [comment]
Hi guys, 
Today we're trying the --store-failures flag, and we're having the same problem of the incremental models.

`15:26:14    When searching for a relation, dbt found an approximate match. Instead of guessing
15:26:14    which relation to use, dbt will move on. Please delete context_testing_dbt_test__audit.not_null_standart_seller_PREF_SELLER_STORE, or rename it to be less ambiguous.`

![image](https://user-images.githubusercontent.com/77084039/190676654-3b233cdc-62e6-4c09-8548-4a15fcb7d516.png)

What could be causing this with incremental models?

**Comment by vargacypher** [comment]
The new Version of dbt-clickhouse==1.2.1 solve the problem.

Thk's guys <3
